objects/TestHarness__mdt.object
<CustomObject>
    <label>TestHarness</label>
    <pluralLabel>TestHarnesses</pluralLabel>
</CustomObject>

objects/TestHarnessData__mdt.object
<CustomObject>
    <description>Relating test data to business processes for use with testing Flow (and Process Builder) to specific data sets for tests</description>
    <fields>
        <fullName>Object_Priority_Index__c</fullName>
        <label>Object Priority Index</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Static_Resource_Object__c</fullName>
        <description>An object with a related static resource for a given test harness</description>
        <inlineHelpText>static resource name should be ObjectAPIName -- moved to text field.</inlineHelpText>
        <label>Static Resource Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>TestHarnesses</relationshipLabel>
        <relationshipName>TestHarnesses</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>TestHarness__c</fullName>
        <label>TestHarness</label>
        <referenceTo>TestHarness__mdt</referenceTo>
        <relationshipLabel>TestHarnessData</relationshipLabel>
        <relationshipName>TestHarnessData</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <label>TestHarnessData</label>
    <pluralLabel>TestHarnessData</pluralLabel>
</CustomObject>

classes/PrioritySelector.cls
// look for existing test harness data for the given object
// If exists, use that priority
// Else find the highest priority used and use the next number

/**
 //Id thID = [SELECT Id FROM TestHarness__mdt WHERE label = 'Bhavana Test' LIMIT 1].Id;
Id thID = [SELECT Id FROM TestHarness__mdt WHERE label = 'Test Priority' LIMIT 1].Id;

system.debug(thID);

System.debug('account ' + PrioritySelector.getPriority('Account', thID));
System.debug('contact ' + PrioritySelector.getPriority('Contact', thID));
System.debug('lead ' + PrioritySelector.getPriority('Lead', thID));
System.debug('Case ' + PrioritySelector.getPriority('Case', thID));


**/
public class PrioritySelector {
    
	private static final Decimal UNDEFINED = -1.00;    
    
    Public static Decimal getPriority(String objectName, Id testHarnessId){
        
        Decimal priority = UNDEFINED;
        
        // get all the thds
        List<TestHarnessdata__mdt> thdList = [SELECT Id, Object_Priority_Index__c, Static_Resource_Object__c
                                              FROM TestHarnessdata__mdt 
                                              WHERE TestHarness__C = :testHarnessId
                                              order BY Object_Priority_Index__c 
                                              DESC
                                             ];

        if(thdList.size() > 0){
            for(TestHarnessdata__mdt thd: thdList){
                if(thd.Static_Resource_Object__c == objectName){
                    priority = thd.Object_Priority_Index__c;
                    break;
                }
            }
            if(priority == UNDEFINED){
                priority = thdList[0].Object_Priority_Index__c + 1;
            }
        } 
        
        // if still undefined, this is the first test harness data being added
        if(priority == UNDEFINED){ 
            priority = 1.00;
        }
        
        system.debug('Returning Priority ' + priority + ' for ' + objectName);
        return priority;
    } 
}